### ISSUE TITLE
alpha.4 breaks features-preview

### ISSUE THREAD

**Issue by zippy** [rust-lang/pin-utils#17]
Alpha.4 breaks code that uses futures-preview-0.3.0-alpha.10 even when compiled against pre-2018-12-26 nightlies.

As of this build [our code](https://github.com/holochain/holochain-rust) (which we build against nightly 2018-11-28) has started breaking. This is mysterious to me because it looks like future-preview-0.3.0-alpha.10 is carefully set to use alpha.3, but these are the errors I get when compiling:

```
error[E0599]: no function or associated item named `get_unchecked_mut` found for type `std::pin::Pin<_>` in the current scope
  --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.10/src/future/map.rs:19:5
   |
19 |     unsafe_unpinned!(f: Option<F>);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `std::pin::Pin<_>`
   |
   = help: did you mean `map_unchecked_mut`?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0599]: no function or associated item named `get_unchecked_mut` found for type `std::pin::Pin<_>` in the current scope
  --> /home/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.10/src/future/inspect.rs:19:5
   |
19 |     unsafe_unpinned!(f: Option<F>);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function or associated item not found in `std::pin::Pin<_>`
   |
   = help: did you mean `map_unchecked_mut`?
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

```

It looks like somehow the pin-utils crate that got uploaded is incorrect or something?  Any help?

**Comment by Nemo157** [comment]
A version constraint without any operator is interpreted as a ["caret requirement"](https://doc.rust-lang.org/nightly/cargo/reference/specifying-dependencies.html#caret-requirements), so `futures-preview@0.3.0-alpha.10` can use any version of `pin-utils` that is semver compatible with `0.1.0-alpha.3`, which `0.1.0-alpha.4` is.

If you want to pin (😉) the version of `pin-utils` used in your project you can add `pin-utils = "=0.1.0-alpha.3"` to your dependencies, Cargo will then use choose `0.1.0-alpha.3` as the sole version used since it satisfies all the version constraints.

Generally `futures-preview` and `pin-utils` are not really trying to keep backwards compatibility during these `alpha` releases, the `std` APIs are moving too fast to make it worthwhile. Now that `pin-utils` is using only stable (on nightly) APIs there might be a first release that will have proper semver compatibility soon.
